### ISSUE TITLE
405 Not Allowed

### ISSUE THREAD

**Issue by duard** [mesaugat/express-api-es6-starter#16]
I clone the repo and start my app but when I try to acess http://localhost:8848/ I get 

```
{
    "error": {
        "code": 405,
        "message": "Method Not Allowed"
    }
}
```

**Comment by mesaugat** [comment]
There's no route defined for http://localhost:8848.

You should try any of these routes:

http://localhost:8848/api
http://localhost:8848/api-docs
http://localhost:8848/api/users

If you go to a route that is not registered it will always send a response that you saw above. You can check the [routes.js](https://github.com/mesaugat/express-api-es6-starter/blob/master/src/routes.js) file for available routes. Every route you add in routes.js file will append `/api` due to https://github.com/mesaugat/express-api-es6-starter/blob/master/src/index.js#L45

**Comment by duard** [comment]
Thanks !
